language: rust

sudo: false

rust: stable

env:
  - RUST_BACKTRACE=full

before_script:
  - rustup component add clippy

script:
  - cargo build
  - cargo clippy -- -D warnings
  - cargo test --verbose
  - make -C test SHARNESS_BUILD_DIRECTORY="$PWD/target/debug" T="cheats-extract*" TEST_OPTS=-v

branches:
  only:
    - master
