language: rust

sudo: false

rust: stable

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --manifest-path codebreaker/Cargo.toml
  - make -C test SHARNESS_BUILD_DIRECTORY="$PWD/target/debug" T="cheats-extract*"

branches:
  only:
    - master
