#!/bin/sh

VF=CB2UTIL-VERSION-FILE

version=$(git describe --tags --match "v[0-9]*" --abbrev=4 --dirty 2>/dev/null ||
	awk '/^v/ {print $1; exit}' HISTORY.md)
version=$(expr "$version" : v*'\(.*\)' | sed -e 's/-/./g')

cur_ver=
if [ -r "$VF" ]; then
	cur_ver=$(sed -e 's/^CB2UTIL_VERSION = //' <$VF)
fi

if [ "$version" != "$cur_ver" ]; then
	echo "CB2UTIL_VERSION = $version"
	echo "CB2UTIL_VERSION = $version" >$VF
fi
